name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn run-script build-and-publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.MARKETPLACE_TOKEN }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension
          path: dist/extension.vsix
